/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../driver/inc/stm32f446re_gpio_driver.h"

int main(void)
{
	GPIO_Handle_t LED2;
	LED2.pGPIOx = GPIOA;
	LED2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	LED2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	LED2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_PeriClockControl(LED2.pGPIOx, ENABLE);
	GPIO_Init(&LED2);
	GPIO_WriteToOutputPin(LED2.pGPIOx, GPIO_PIN_NO_5, 1);
	for(;;);
}
