/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../driver/inc/stm32f446re_gpio_driver.h"

GPIO_Handler *led2;
GPIO_Handler *user_botton;


int main(void)
{
	led2 = new GPIO_Handler(GPIOA,
							GPIO_PIN_NO_5,
							GPIO_MODE_OUT,
							GPIO_SPEED_LOW,
							GPIO_OP_TYPE_PP,
							GPIO_NO_PUPD,
							IRQ_Prio_NO_15);

	user_botton = new GPIO_Handler(GPIOC,
								   GPIO_PIN_NO_13,
								   GPIO_MODE_IT_FT,
								   GPIO_SPEED_FAST,
								   IRQ_Prio_NO_15);
	led2->gpio_write_to_output_pin(1);
	while(1);
}

extern "C" {
	void EXTI15_10_IRQHandler(void) {
		// handle the interrupt
		led2->gpio_toggle_output_pin();
		user_botton->gpio_irq_handling();
	}
}

