/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../driver/stm32f446re_uart_driver.h"

uart_handler uart4(UART4, UART_MODE_TXRX, UART_STD_BAUD_115200, UART_STOPBIT_1,
                   UART_WORDLEN_8BITS, UART_PARITY_DISABLE,
                   UART_HW_FLOW_CTRL_NONE);

int main(void) {
  uart4.init();
  /* Loop forever */
  for (;;)
    ;
}
